### ISSUE TITLE
http://go.microsoft.com/fwlink/?LinkId=527962

### ISSUE THREAD

**Issue by ibrahim-1303** [dotnet/EntityFramework.Docs.tr-tr#4]
[Geri bildiriminizi buraya girin]

---
#### Belge Ayrıntıları

⚠ *Bu bölümü düzenlemeyin. docs.microsoft.com ➟ GitHub sorunu bağlantısı için gereklidir.*

* ID: 649fbab8-b960-6873-14bf-188d14757fee
* Version Independent ID: f5ee3135-54c8-689c-e28b-b203b376bd6f
* Content: [Eşzamanlılık çakışmalarını işleme-EF Core](https://docs.microsoft.com/tr-tr/ef/core/saving/concurrency)
* Content Source: [entity-framework/core/saving/concurrency.md](https://github.com/dotnet/EntityFramework.Docs.tr-tr/blob/live/entity-framework/core/saving/concurrency.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by Rick-Anderson** [comment]
@ibrahim-1303  can you please describe the problem?
