### ISSUE TITLE
Markdown Tabs Duplicated

### ISSUE THREAD

**Issue by ammoti** [dotnet/EntityFramework.Docs.tr-tr#5]
Hi,
I guess, code-markdown tabs under "Composite index" section duplicated in Turkish translate.
I am glad to find something worth it open issue :).

---
#### Belge Ayrıntıları

⚠ *Bu bölümü düzenlemeyin. docs.microsoft.com ➟ GitHub sorunu bağlantısı için gereklidir.*

* ID: f85ea32c-8d23-d61d-6036-cd772e3e95d9
* Version Independent ID: 25dd8ac4-2521-5200-0ddf-63ac8c83787a
* Content: [Dizinler-EF Core](https://docs.microsoft.com/tr-tr/ef/core/modeling/indexes?tabs=data-annotations)
* Content Source: [entity-framework/core/modeling/indexes.md](https://github.com/dotnet/EntityFramework.Docs.tr-tr/blob/live/entity-framework/core/modeling/indexes.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
Duplicate of https://github.com/dotnet/EntityFramework.Docs/issues/2900

**Comment by ammoti** [comment]
> Duplicate of [dotnet/EntityFramework.Docs#2900](https://github.com/dotnet/EntityFramework.Docs/issues/2900)

Thank you I did not realize that

**Comment by JasonCard** [comment]
This issue is now fixed :)
